### ISSUE TITLE
unexpected error when retrying exceeds 3 times

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/dpdispatcher#124]
unexpected error when retrying exceeds 3 times
```
Traceback (most recent call last):
 File "/home/jz748/anaconda3/lib/python3.7/site-packages/dpdispatcher/submission.py", line 215, in handle_unexpected_submission_state
job.handle_unexpected_job_state()
File "/home/jz748/anaconda3/lib/python3.7/site-packages/dpdispatcher/submission.py", line 532, in handle_unexpected_job_state
raise RuntimeError(f"job:{self.job_hash} {self.job_id} failed {self.fail_count} times.job_detail:{self}")
RuntimeError:  (delete here)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jz748/anaconda3/bin/dpgen", line 33, in <module>
    sys.exit(load_entry_point('dpgen', 'console_scripts', 'dpgen')())
  File "/home/jz748/codes/dpgen/dpgen/main.py", line 175, in main
    args.func(args)
  File "/home/jz748/codes/dpgen/dpgen/generator/run.py", line 2942, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/home/jz748/codes/dpgen/dpgen/generator/run.py", line 2928, in run_iter
    run_fp (ii, jdata, mdata)
  File "/home/jz748/codes/dpgen/dpgen/generator/run.py", line 2395, in run_fp
    forward_common_files=forward_common_files)
  File "/home/jz748/codes/dpgen/dpgen/generator/run.py", line 2339, in run_fp_inner
    submission.run_submission()
  File "/home/jz748/anaconda3/lib/python3.7/site-packages/dpdispatcher/submission.py", line 182, in run_submission
    self.handle_unexpected_submission_state()
  File "/home/jz748/anaconda3/lib/python3.7/site-packages/dpdispatcher/submission.py", line 219, in handle_unexpected_submission_state
    f"Meet errors will handle unexpected submission state.\n"
AttributeError: 'Submission' object has no attribute 'remote_root'
```

**Comment by njzjz** [comment]
The first exception is expected, but the second is not...
