### ISSUE TITLE
Dealing with unknown error sometimes occured caused by accidental issue

### ISSUE THREAD

**Issue by Cloudac7** [deepmodeling/dpdispatcher#208]
For now, we just check the status of each job task by executing commands such as `bjobs <JobID>` and just checking the `stdout` then to get whether the job is running, finished or failed. However, now for LSF, Slurm as well as PBS, it just raise an `RuntimeError` to show that there is something wrong with the task and stop the process. Like this:

```
Traceback (most recent call last):
  ...
  File "/data/home/xxx/.local/lib/python3.8/site-packages/dpdispatcher/submission.py", line 536, in get_job_state
    job_state = self.machine.check_status(self)
  File "/data/home/xxx/.local/lib/python3.8/site-packages/dpdispatcher/lsf.py", line 104, in check_status
    raise RuntimeError("status command bjobs fails to execute.\n error info: %s \nreturn code %d\n"
RuntimeError: status command bjobs fails to execute.
 error info:
return code 255
```

As a long workflow run goes, it might just be a network issue causing such 255 error code. When manually resubmitting the task, it just continue running with nothing wrong happened. DPDispatcher process just exited even if the error occured as few as one time. For job level issue, there is just a tolerance as many as 3 times for job to be resubmitted itself.

Should a be added to just make the workflow not stopped by such an accidental error? Like adding a retry process?

**Comment by Cloudac7** [comment]
A universal implementation by @njzjz. Thanks.
#218
