### ISSUE TITLE
Wildcards in `backward_files` failed if the number of files > 100 in `SSHContext`

### ISSUE THREAD

**Issue by LavendaRaphael** [deepmodeling/dpdispatcher#293]
dpdispatcher: v0.4.18
context_type: SSHContext

If I use wildcard in `backward_files` of `task.json` and the number of total files in all tasks > 100, after the tasks complete, the dpdispatcher raise error.

`task.json`

```json
...
    "backward_files": [
        "restart.*"
    ],
...
```

Error

```
faye@faye:~/research_d/$ python sub.py 
2022-12-24 14:00:05,675 - INFO : Find old submission; recover submission from json file;submission.submission_hash:bd11d2674bd4ccc227e318637f184e03ee9126f8; machine.context.remote_root:/public/spst/home/dpdispatcher/bd11d2674bd4ccc227e318637f184e03ee9126f8; submission.work_base:..;
2022-12-24 14:00:16,838 - INFO : info:check_all_finished: True
Traceback (most recent call last):
  File "sub.py", line 58, in <module>
    submission.run_submission()
  File "/home/faye/.local/lib/python3.9/site-packages/dpdispatcher/submission.py", line 217, in run_submission
    self.download_jobs()
  File "/home/faye/.local/lib/python3.9/site-packages/dpdispatcher/submission.py", line 349, in download_jobs
    self.machine.context.download(self)
  File "/home/faye/.local/lib/python3.9/site-packages/dpdispatcher/ssh_context.py", line 514, in download
    self._get_files(file_list, tar_compress = self.remote_profile.get('tar_compress', None))
  File "/home/faye/.local/lib/python3.9/site-packages/dpdispatcher/ssh_context.py", line 698, in _get_files
    self.block_checkcall('tar %s %s -T %s' % (tar_command, of, file_list_file))
  File "/home/faye/.local/lib/python3.9/site-packages/dpdispatcher/ssh_context.py", line 537, in block_checkcall
    raise RuntimeError("Get error code %d in calling %s through ssh with job: %s . message: %s" %
RuntimeError: Get error code 2 in calling tar cfh bd11d2674bd4ccc227e318637f184e03ee9126f8.tar -T /public/spst/home/dpdispatcher/bd11d2674bd4ccc227e318637f184e03ee9126f8/.tmp.tar.f38bd1f6-65c4-4fc1-b6de-640a41650ddb through ssh with job: bd11d2674bd4ccc227e318637f184e03ee9126f8 . message: tar: 0/restart.*: Cannot stat: No such file or directory
tar: 1/restart.*: Cannot stat: No such file or directory
...
```

I track the error log to code

https://github.com/deepmodeling/dpdispatcher/blob/8b5b2c8df62cd1495af3491b80170ada7d33d593/dpdispatcher/ssh_context.py#L740-L750

**Comment by njzjz** [comment]
The wildcard is never supported in `backward_files`.

**Comment by LavendaRaphael** [comment]
> The wildcard is never supported in `backward_files`.

OK, Got it. But it works when number of files is not too much. I found a issue about uploading #102.
